# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reference.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'reference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freference.proto\x12\x12\x62\x65llo.reference.v1\"M\n\x15WatchReferenceRequest\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x1a\n\x12robot_model_sha256\x18\x02 \x01(\t\"\x9b\x01\n\x13ReferenceStreamInfo\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\r\n\x05robot\x18\x02 \x01(\t\x12\x1a\n\x12robot_model_sha256\x18\x03 \x01(\t\x12\x13\n\x0bjoint_names\x18\x04 \x03(\t\x12\x11\n\tsource_id\x18\x05 \x01(\t\x12\x17\n\x0fnominal_rate_hz\x18\x06 \x01(\x01\"\xa8\x02\n\x0eReferenceFrame\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x1b\n\x13source_monotonic_ns\x18\x02 \x01(\x04\x12\x1f\n\x17root_translation_metres\x18\x03 \x03(\x01\x12\x1d\n\x15root_orientation_wxyz\x18\x04 \x03(\x01\x12\"\n\x1aroot_linear_velocity_local\x18\x05 \x03(\x01\x12#\n\x1broot_angular_velocity_local\x18\x06 \x03(\x01\x12\x16\n\x0ejoint_position\x18\x07 \x03(\x01\x12/\n\x04mode\x18\x08 \x01(\x0e\x32!.bello.reference.v1.ReferenceMode\x12\x15\n\rsample_age_ms\x18\t \x01(\x04\"\x91\x01\n\x16WatchReferenceResponse\x12\x37\n\x04info\x18\x01 \x01(\x0b\x32\'.bello.reference.v1.ReferenceStreamInfoH\x00\x12\x33\n\x05\x66rame\x18\x02 \x01(\x0b\x32\".bello.reference.v1.ReferenceFrameH\x00\x42\t\n\x07payload*|\n\rReferenceMode\x12\x1e\n\x1aREFERENCE_MODE_UNSPECIFIED\x10\x00\x12\x19\n\x15REFERENCE_MODE_ACTIVE\x10\x01\x12\x17\n\x13REFERENCE_MODE_HOLD\x10\x02\x12\x17\n\x13REFERENCE_MODE_STOP\x10\x03\x32}\n\x10ReferenceService\x12i\n\x0eWatchReference\x12).bello.reference.v1.WatchReferenceRequest\x1a*.bello.reference.v1.WatchReferenceResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFERENCEMODE']._serialized_start=723
  _globals['_REFERENCEMODE']._serialized_end=847
  _globals['_WATCHREFERENCEREQUEST']._serialized_start=39
  _globals['_WATCHREFERENCEREQUEST']._serialized_end=116
  _globals['_REFERENCESTREAMINFO']._serialized_start=119
  _globals['_REFERENCESTREAMINFO']._serialized_end=274
  _globals['_REFERENCEFRAME']._serialized_start=277
  _globals['_REFERENCEFRAME']._serialized_end=573
  _globals['_WATCHREFERENCERESPONSE']._serialized_start=576
  _globals['_WATCHREFERENCERESPONSE']._serialized_end=721
  _globals['_REFERENCESERVICE']._serialized_start=849
  _globals['_REFERENCESERVICE']._serialized_end=974
# @@protoc_insertion_point(module_scope)
